version: '3'
services:
  nginx_lb:
    build: ./nginx
    privileged: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - server_net

  nginx:
    depends_on:
      - nginx_lb
    build: ./nginx
    privileged: true
    networks:
      - server_net
    deploy:
      replicas: 3

  client:
    build: ./base
    privileged: true
    networks:
      - client_net
    deploy:
      replicas: 4
    command: sh -c "/sbin/ip route replace default via 10.0.1.254 && apt install -y apache2-utils && ab -k -c 100 -n 100000 10.0.2.2/"
    tty: true
    depends_on:
      - router

  router:
    build: ./base
    container_name: router
    hostname: router
    privileged: true
    networks:
      client_net:
        ipv4_address: 10.0.1.254
      server_net:
        ipv4_address: 10.0.2.254

networks:
  client_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1
  server_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
          gateway: 10.0.2.1

