networks:
  external:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.255.0/24
          gateway: 172.31.255.1
  public1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.123.128/28
          gateway: 172.16.123.129
  public2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.123.144/28
          gateway: 172.16.123.145
  internal1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/29
          gateway: 10.0.1.1
  internal2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.8/29
          gateway: 10.0.1.9
  internal3:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.16/29
          gateway: 10.0.1.17

services:
  router1:
    build: ./base
    container_name: ospf-router1
    networks:
      external:
        ipv4_address: 172.31.255.253
      internal1:
        ipv4_address: 10.0.1.2
      internal2:
        ipv4_address: 10.0.1.10
    volumes:
      - ./config/ospfd.conf:/etc/quagga/ospfd.conf
      - ./config/zebra.conf:/etc/quagga/zebra.conf
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always
    privileged: true

  router2:
    build: ./base
    container_name: ospf-router2
    networks:
      public2:
        ipv4_address: 172.16.123.158
      internal3:
        ipv4_address: 10.0.1.18
      internal2:
        ipv4_address: 10.0.1.11
    volumes:
      - ./config/ospfd.conf:/etc/quagga/ospfd.conf
      - ./config/zebra.conf:/etc/quagga/zebra.conf
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always
    privileged: true

  router3:
    build: ./base
    container_name: ospf-router3
    networks:
      public1:
        ipv4_address: 172.16.123.142
      internal3:
        ipv4_address: 10.0.1.19
      internal1:
        ipv4_address: 10.0.1.3
    volumes:
      - ./config/ospfd.conf:/etc/quagga/ospfd.conf
      - ./config/zebra.conf:/etc/quagga/zebra.conf
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always
    privileged: true

  user1:
    build: ./base
    container_name: user1
    networks:
      public1:
        ipv4_address: 172.16.123.130
    command: sh -c "/sbin/ip route replace default via 172.16.123.142 && /bin/bash"
    tty: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always
    depends_on:
      - router3

  user2:
    build: ./base
    container_name: user2
    networks:
      public2:
        ipv4_address: 172.16.123.146
    command: sh -c "/sbin/ip route replace default via 172.16.123.158 && /bin/bash"
    tty: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always
    depends_on:
      - router2




