networks:
  external:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.255.0/24
          gateway: 69.0.1.1
  public1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.123.128/28
          gateway: 69.0.2.1
  public2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.123.144/28
          gateway: 69.0.3.1
  internal1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/29
          gateway: 69.0.1.1
  internal2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.8/29
          gateway: 69.0.2.1
  internal3:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.16/29
          gateway: 69.0.3.1

services:
  router:
    build: ./base
    container_name: ospf-router
    networks:
      net1:
        ipv4_address: 69.0.1.254
      net2:
        ipv4_address: 69.0.2.254
      net3:
        ipv4_address: 69.0.3.254
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always
